Models/ButtonModel.cs
namespace ButtonGrid.Models
{
    public class ButtonModel
    {
        public int Id { get; set; }

        public int ButtonState { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ButtonGrid.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ButtonController.cs
using ButtonGrid.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace ButtonGrid.Controllers
{
    public class ButtonController : Controller
    {
        static List<ButtonModel> buttons = new List<ButtonModel>();
        Random random = new Random();
        const int GRID_SIZE = 25;
        public IActionResult Index()
        {
            if (buttons.Count < GRID_SIZE)
            {
                for (int i = 0; i < GRID_SIZE; i++)
                {
                    buttons.Add(new ButtonModel { Id = i, ButtonState = random.Next(4) });
                }
            }
            return View("Index", buttons);
        }
        public IActionResult HandleButtonClick(string buttonNumber)
        {
            // convert from string to int
            int bN = int.Parse(buttonNumber);

            buttons.ElementAt(bN).ButtonState = (buttons.ElementAt(bN).ButtonState + 1) % 4;

            return View("index", buttons);
        }

        public IActionResult ShowOneButton(int buttonNumber) 
        {
            // add one to the button state. if >4, then reset to 0
            buttons.ElementAt(buttonNumber).ButtonState = (buttons.ElementAt(buttonNumber).ButtonState + 1) % 4;

            // 1. Render a button and save it to a string
            string buttonString = RenderRazorViewToString(this, "ShowOneButton", buttons.ElementAt(buttonNumber));
            // 2. Generate a win or loss string base on the state of the buttons array
            bool DidIWinYet = true;
            for (int i = 0; i < buttons.Count; i++)
            {
                if (buttons.ElementAt(i).ButtonState != buttons.ElementAt(0).ButtonState)
                    DidIWinYet = false;
            }
            string messageString = " ";
            if (DidIWinYet == true)
                messageString = "<p> Congratulations. All of the buttons are the same color.</p>";
            else
                messageString = "<p> Not all of the buttons are the same color. See if you can make them match.</p>";
            // 3. Assembly a JSON string that has tow parts (button string html and win loss message)
            var package = new { part1 = buttonString, part2 = messageString };
            // 4. Send the JSON result.
            return Json(package);
            // 5. In the site .js file, the data will have to be interpreted as two pieces of data instead of one
            // --> site.js
        }
        public static string RenderRazorViewToString(Controller controller, string viewName, object model = null)
        {
            controller.ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                IViewEngine viewEngine =
                    controller.HttpContext.RequestServices.GetService(typeof(ICompositeViewEngine)) as ICompositeViewEngine;
                ViewEngineResult viewResult = viewEngine.FindView(controller.ControllerContext, viewName, false);

                ViewContext viewContext = new ViewContext(
                    controller.ControllerContext,
                    viewResult.View,
                    controller.ViewData,
                    controller.TempData,
                    sw,
                    new HtmlHelperOptions()
                );
                viewResult.View.RenderAsync(viewContext);
                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

Controllers/HomeController.cs
using ButtonGrid.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ButtonGrid.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Button/Index.cshtml
@model IEnumerable<ButtonGrid.Models.ButtonModel>

    <!--td= table data-->
    <!--td= table header-->

 
<style>
        .game-button{
            width:90px;
            text-align:center;
            border:none;
        }

        .game-button-image{
            width:80%
        }

        .button-zone{
            display:flex;
            flex-wrap:wrap;
        }

        .line-break{
            flex-basis:100%;
            height:0;
        }

        .button-label{
            font-size:10px;
            text-align:center;
        }
</style>


@{
    // store image names in an array for more efficent code
    string[] imagenames = { "buttonGreen.png", "buttonRed.png", "buttonTeal.png", "buttonYellow.png" };
}

<!--Durch das Form wird dieser Teil interaktiv-->
<p>Kontrollzeit Ajax: @DateTime.Now</p>
<form>
        <div class="button-zone">
            @for (int i = 0; i < Model.Count(); i++)
            {
                // start new line every five elements
                if (i % 5 == 0)
                {
                    <div class="line-break"> </div>
                }
                    <div class="oneButton" id=@i>
                        <!-- der asp-controller sagt welcher teil von den controllern zuhört-->
                        <button class="game-button" type="submit" value="@Model.ElementAt(i).Id" name="buttonNumber" asp-controller="Button" asp-action="HandleButtonClick">
                            <!--show the proper image according to the button state property-->
                            <img class="game-button-image" src="~/img/@imagenames[Model.ElementAt(i).ButtonState]"/>
                            <!--zeigt button farbe als nummer und positionsnummer im grid-->
                            <div class="button-label">
                                @Model.ElementAt(i).Id, 
                                @Model.ElementAt(i).ButtonState
                            </div>
                        </button>
                    </div>
            }
        </div>
</form>
<div id ="messageArea">
    <p>Not all the buttons are the same color. See if you can make them all match.</p>
</div>
                    

Views/Button/ShowOneButton.cshtml
@model ButtonGrid.Models.ButtonModel

@{
    // store image names in an array for more efficent code
    string[] imagenames = { "buttonGreen.png", "buttonRed.png", "buttonTeal.png", "buttonYellow.png" };
}


<button class="game-button" type="submit" value="@Model.Id" name="buttonNumber" asp-controller="Button" asp-action="HandleButtonClick">
    <img class="game-button-image" src="~/img/@imagenames[Model.ButtonState]" />
    <div class="button-label">
        @Model.Id,
        @Model.ButtonState
    </div>
</button>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Willkommen zum ButtonGrid Projekt</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ButtonGrid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ButtonGrid.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ButtonGrid</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Button" asp-action="Index">Button Grid</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ButtonGrid - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>